name: driver-license-platform
region: nyc

services:
- name: api
  github:
    repo: goutham432/Driver_License_App
    branch: main
    deploy_on_push: true
  dockerfile_path: Dockerfile
  http_port: 5000
  instance_count_slug: basic-xxs
  instance_size_slug: basic-xxs
  routes:
  - path: /
  health_check:
    http_path: /health
    initial_delay_seconds: 30
    period_seconds: 10
    timeout_seconds: 3
    success_threshold: 1
    failure_threshold: 3
  envs:
  - key: NODE_ENV
    value: production
  - key: PORT
    value: "5000"
  - key: MONGODB_URI
    value: ${db.MONGODB_URI}
    scope: RUN_TIME
    type: SECRET
  - key: JWT_SECRET
    value: ${JWT_SECRET}
    scope: RUN_TIME
    type: SECRET
  - key: CLIENT_URL
    value: ${APP_URL}
    scope: RUN_TIME

databases:
- name: db
  engine: MONGODB
  version: "7"
  production: false
  db_name: driver-license-platform
